### ISSUE TITLE
test coverage

### ISSUE THREAD

**Issue by dqdinh** [Day8/re-frame#109]
Are there plans to add more test coverage?

https://github.com/Day8/re-frame/blob/master/project.clj#L25

**Comment by danielcompton** [comment]
Patches welcome :)

**Comment by danielcompton** [comment]
Remembering that tests have a maintenance cost too, I'm not sure which parts @mike-thompson-day8 would want tests written for.

**Comment by mike-thompson-day8** [comment]
Since release, I don't remember there being a single bug, which empirically indicates (to me) that the current test coverage is broadly right :-)  

Having said that, tests are often more about future bugs  (I'm actually very pro unit tests,  but not compulsively or systemically so).  I just hasn't felt as if there were many parts of the code which were complicated enough to warrant tests (which, as Daniel said, do cost a lot).   I seem to remember that the `on-change` middleware was the only function where I really felt like a test was necessary.
