### ISSUE TITLE
Referred var reagent.impl.batching/do-later does not exist 

### ISSUE THREAD

**Issue by favetelinguis** [Day8/re-frame#140]
Im getting the following error when trying to run a very minimal re-frame app. Not sure where this error is coming from, why are we trying to find do-later in batching? There is no such def in batching...

clojure
Compiling "resources/public/js/compiled/hello_world.js" from ["src-cljs"]...
{:tag :cljs/analysis-error}
ANALYSIS ERROR: Referred var reagent.impl.batching/do-later does not exist on file null, line null, column null
clojure

Im using the following versions:
[reagent "0.5.1"]
[re-frame "0.6.0"]

**Comment by mike-thompson-day8** [comment]
You have two choices in terms of the dependencies you use (in `project.clj`)
   - `[reagent "0.5.1"]` goes with `[re-frame "0.6.0"]`
   - `[reagent "0.6.0-alpha"]`  goes with `[re-frame "0.7.0-alpha"]`

The first option is easiest, and probably preferred.  

The second option is more complicated because `[re-frame "0.7.0-alpha"]` is not available in clojars yet.  You'll have to check out `master` from this repo and `lein install` it into your local maven repo.

**Comment by favetelinguis** [comment]
Ok thanks. Works now
