### ISSUE TITLE
"Trade-offs" section to readme?

### ISSUE THREAD

**Issue by ghost** [Day8/re-frame#160]
The readme for re-frame is top-notch, but it would be a great addition to have a section on "can't do, doesn't cover, doesn't try to do, makes difficult" in the essence of full transparency. 

Often a library / framework proclaims loudly all the wondrous things it can accomplish, and marvelous feats of complexity it tackles in a simple way. As potential users of a library, I almost immediately look for the things a library is trying to hide. Does performance suck? Does the mental model break down at scale? Is it impossible to have a large team work in parallel? Does the framework help you pour concrete, and hide that fact, until everything has dried?

If I can't find these tradeoffs relatively quickly, I become very skeptical and am likely to move on.

I personally haven't used reframe for anything but trivial exploration. It would be great to get input from people who have worked on non-trivial applications at scale over extended periods. That is a lot of qualifiers, but too often I see arguments on ghissues or ggroups or reddit claiming "my non-trivial application I spent 3 months developing went swimmingly and there are no issues". A 3 month project is almost by definition trivial.

Personally, I would be interested in areas around these points, but I welcome any and all feedback from others:
- modularity/composability/fractability - can you create a completely independent module and have N copies of that module? Can you reuse such a module across applications? Can you have N copies of a module each containing M copies of a nested module, again, without crossing wires? Can you run two independent copies of your app side-by-side in different divs? I can't tell you how many frameworks out there require you to re-write modules in significant ways in order to make them "portable", and some simply disallow it entirely. I'm not entirely sure how re-frame could handle these cases, if at all.
- coordination - complex web-apps often have deep-linking (not in the url sense) between states/views/workflows. A particular weakness I find with a lot of event-driven/top-down style architectures is that coordinating decoupled pieces becomes tedious, if not impossible. Imagine a user is browsing a pie chart, and wants to click on a slice. Perhaps this takes you to an entirely different part of the application, which requires 1) swapping the main context from "charts" to "deep analysis" 2) loading up data from the selection into a handful of deeper-analysis views 3) swapping out toolbars / selections in  other components to reflect the deep link. This kind of linking has been a requirement of _nearly all_ applications I have built in the last few years. One potential pain-point I see immediately with re-frame is the 1-to-1 event / handler requirement. If `[:pie-slice-clicked]` can only be caught by 1 module, how can you coordinate this dance without coupling modules in unseemly ways?
- middleware - this isn't a weakness of re-frame, more just a design decision, but I would be interested to hear how people feel about having to attach middleware to each handler independently? I have always thought middleware were orthogonal, app-wide wrappers initialized once and forgotten. I find it strange that re-frame has a per-handler middleware scenario. 

Thanks for your time,
~luke

**Comment by aft-luke** [comment]
To give some context around the first point (modularity).. there's a [whole project dedicated](https://github.com/slorber/scalable-frontend-with-elm-or-redux) to addressing issues that come up in a redux-style architecture, which closely matches re-frame. The gist is that redux is not designed with modularity in mind, and consequently larger-scale apps start to collapse under complexity arising from the inability to reuse components (and also communication of side-effects between components). Worth a glance.

**Comment by mike-thompson-day8** [comment]
@aft-luke   I agree with your sentiment and the need.

But I've been put off writing up something because: 
  - my SPAs tend to be a bit unusual - I'm inexperienced in many more common usecases.  I'd hesitate to hold forth with opinions without real experience (of, say deep linking). 
  - such assessments require quite broad knowledge of alternatives technologies.  Everything is relative. 
 
So ... I would encourage others to add their own experiences in here, so we accumulate a picture (good and bad),

**Comment by Arcanum-XIII** [comment]
After having some fun with re-frame, coming from om(.now, not .next since it would entails me to relearn everything and live again on a dangerous bleeding edge lacking documentation), I guess I could at least give some opinion about @aft-luke question :
• a per handler middleware is for me needed. I have varying data source type, and it's easier to configure each handler for the specificity of those. There's of course some tediousness added if you use some nearly everywhere, but well, nothing stop us to write another middleware to take care of that, so not bothering me a lot. 
• as per coupling, I found that most component seem to cascade their coupling. The pie-chart example would trigger one event, that would start a cascade of events. The good thing about this is, for me at least, that it's easy to test a restricted version of this cascade. Having written a lot of traditionnal mvc app, this is clearly very refreshing since I don't have to fight this coupling : it doesn't exist per se, it's only some configuration change. 
Anecdote : I have a main component that only handle navigation. In it I load the sub component needed : each will then check in the db if they need to do anything, load more component, and all that individually. 
• I would too be curious to see how create "library" component. My next app willuse the re-com library, so I will maybe have a better idea on how @mike-thompson-day8  handle this, but for now it's a bit mysterious. Maybe something that can be improved in the documentation ?

The only real limitation is the react ones from my PoV, like how to properly animate stuff for example.

**Comment by mike-thompson-day8** [comment]
I'm certainly interested in reading such a considered piece, but as I indicated earlier, I'm not the one to write it.  I'm biased and I don't have broad experience. I'll leave that to the blog posts of others. 

I'm in cleanup mode, so I'm going to close this.
