### ISSUE TITLE
Overwriting subscription-handler for: :get-options

### ISSUE THREAD

**Issue by arichiardi** [Day8/re-frame#165]
Hey folks! 
I bumped re-frame and now I am receiving the following warning

`re-frame: overwriting subscription-handler for: :get-options`

Nothing bad, I just wanted to understand what it is, is it complaining because I have two `get-options` handlers in my code base?

(In which case it is very great)

**Comment by LukasRychtecky** [comment]
Hi,
yes it's complaining because you have two subs handlers with same name. I guess that first sub handler will be skipped.

**Comment by arichiardi** [comment]
Mmm...I checked and I have actually only one, does this count as double?

```
(register-sub
 :get-options
 (fn [db [_ console-key]]
   (make-reaction (fn get-options [] (get-in @db [:autocomplete :linked-components console-key :options])))))
```

I assigned a name there following the debugging suggestions...
Another question would be, do subs other namespaces count?

**Comment by mike-thompson-day8** [comment]
@arichiardi  re-frame is reporting that that you are registering an Subscription Handler for `:get-options` twice.  The 2nd registration will overwrite the first (and that's the point at which you see the warning). 

Perhaps you are using figwheel, leading to the same file being loaded a 2nd time?

To answer your question, Subscription Handlers are separate to Event Handlers. So you could register a Subscription Handler for `:get-options` and an Event Handler for `:get-options` and you'd see no warnings. 

I'll close this because there's no re-frame bug here..  Please continue with this in slack or news groups.

**Comment by arichiardi** [comment]
:+1:
