### ISSUE TITLE
Add pre-event callback hook capability

### ISSUE THREAD

**Issue by mike-thompson-day8** [day8/re-frame#236]
Add a way to register a handler `fn` to will be called immediately before each event is processed, with the event as the only arg. 

Among other things, will allow for easier logging in certain cases.

**Comment by superstructor** [comment]
How is this different to interceptors ?

**Comment by danielcompton** [comment]
The new (experimental) re-frame tracing partially covers this.

**Comment by hipitihop** [comment]
My specific use case is to be able to maintain an history of every event (prior to being handled) 
- need full event vec (prior e.g. trim-v)
- interceptor/call-back decides what it means to log (in my case I want to maintain actual history list of event vectors) and may optionally filter out some events, or otherwise stub out event elements.
- I don't want to specially instrument EVERY handler throughout my code base via reg-event-* or my own versions of those.
- I don't need to modify or effect the event in the chain, but I can see where others may have that requirement

**Comment by flexsurfer** [comment]
hey guys, any news? :)

**Comment by mike-thompson-day8** [comment]
I'm going to close this.  I don't think we need this specific capability. You can now add a global interceptor which will do a good enough job.
