### ISSUE TITLE
register-sub middleware

### ISSUE THREAD

**Issue by whodidthis** [Day8/re-frame#25]
You probably get asked for this a lot but would be cool if one could use the same or similar middleware for register-sub too, at least path and trim-v. 

Often when dealing with page-specific stuff one writes stuff like
```clojure
(def path [:page :login])
(def path-m (re-frame.core/path path))

(register-handler
  ::input-changed
  path-m
  (fn [db' [_ value]]
    (assoc db' :value value)))

(register-sub
  ::input
  (fn [db _]
    (reaction (get-in @db (conj path :value)))))
```
But it would be cool to be able to derive the db in register-sub too
```clojure
(register-sub 
  ::input
  path-m
  (fn [db' _]
    (reaction (:value @db'))))

**Comment by mike-thompson-day8** [comment]
@whodidthis  Thanks for the feedback.  I am actively working on this stuff for v0.3.0, hopefully in a week.  Design is still not quite settled in my mind.  Slightly different needs to handlers.

**Comment by whodidthis** [comment]
Also I was wondering if you had any magic beans for the actual dom elements for when you sadly have to call functions like focus and blur on them.

I thought about doing something like 
```clojure
(defn my-view []
  [:form {:on-submit #(dispatch [::submit])}
    [text-field {:ref ::input ...etc}]])

(defn text-field [{ref :ref}]
  ;save the dom element to state
  (dispatch [::element ref (.getDOMElement reagent.impl.component/*current-component*)])
  [:input ...]))

(register-handler
  ::element
  (fn [db [_ ref element]]
    (assoc db ref element)))
```
in order to be able to use the element when needed
```clojure
(register-handler
  ::submit
  ; send to places

(register-handler
  ::response
  (fn [db [_ [success error]]]
    (if success
      (do (.blur (::input db)) ;etc
```
Is a bit of manual work so was wondering if there's anything better "out there"

**Comment by mike-thompson-day8** [comment]
Ouch.  There does seem to be some problems here.  
First, we only ever want to be `dispatching` pure data (not DOM Elements)
Second, we want our components to be a function of `app-db`  ... but that `text-field` you have is actively dispatching  in order to "get itself" into a particular state. 

Can you supply some more context?  I'm sensing that you have an event happen (form submit?) and, in response, you want a particular text field to get focus?

**Comment by whodidthis** [comment]
Yes, basically I want a visitor to type on a form field and submit it (request login token to email), and when the server responds OK, reveal and focus an other field (where token can be typed in).

Not that this wouldn't be a problem in any cljs react library heh

**Comment by mike-thompson-day8** [comment]
I'd suggest something like this:

1.  have some piece of `app-db` to say what logical state the app is in:  `user-entering`, `user-clicked-submitted`, `got-answer-is-back-from-server`
2. Put the revealed input into its own component, and include it via this:
     ```
      (when   (= @logical-state  :got-answer-is-back-from-server)
             [extra-input-component]             ;;   it won't initially be there.
    ```
3.  Add a [life-cycle](http://facebook.github.io/react/docs/component-specs.html)  `component-did-mount` method to that `extra-input-component` and, in that lifecycle method, force focus on the input field, brute force.
    ```
      (.focus (.getElementById js/document  "id-of-input-field") )    ;; very approximately
    ```  

So, in effect, when the component is first created and put into the DOM, the input field will be given focus.  But then we never worry about it again. 

[Look here for hints](https://github.com/Day8/re-frame/wiki/Creating-Reagent-Components#form-3-a-class-with-life-cycle-methods) on adding lifecycle methods:

**Comment by whodidthis** [comment]
Too bad react doesnt have a "get element x from within this component and its children" thingie so I guess I'll agree with the document.getElementById().

Although I do wonder if I should try to make a text field listen for a props value as a kind of a signal to focus on component-did-mount and component-will-update.

Something around
```clojure
(defn text-field [{focus :focus}]
  (let [last-focus (atom focus)]
    (reagent/create-class
      {:component-will-update
       (fn [this {focus :focus}]
         (when (and focus (not= @last-focus focus))
           (reset! last-focus focus)
           (.focus (.getDOMElement this))))
       :reagent-render
       (fn [props]
         [:input ;etc
```

**Comment by whodidthis** [comment]
Also any chance of getting the original event as an argument to `after` middleware?
```clojure
(register-handler
  :route/set
  (after (fn [{new-route :route} [_ route]
           (when-not (= new-route route)
             (route-set new-route))))
  (fn [db [_ route]]
    (let [roles (:roles db)
          required-roles (get permissions route)]
      (if (clojure.set/subset? required-roles roles)
        (assoc db :route route)
        (assoc db :error "no permissions"))))
```
Maybe a little bit using `after` for the sake of using it but anyways heh

**Comment by mike-thompson-day8** [comment]
Yeah, I see what you mean.  I'll make that change in  v0.3.0.  Will be backwards compatible because the 2nd parameter `v` will just be ignored by any existing code.

Remember, that middleware is very easy to write yourself.  Only 9 lines of code, 6 of them  boilerplate. You don't have to stick with what is supplied.

**Comment by marcloyal3** [comment]
Interesting discussion.

Just curious about the comment here:

"Too bad react doesnt have a "get element x from within this component and its children" thingie so I guess I'll agree with the document.getElementById()."

Doesn't reagent/current-component return an object from which reagent/dom-node can produce the React DOM element?

**Comment by mike-thompson-day8** [comment]
Indeed, reagent does have `reagent/dom-node`.  But you'd then have to be putting the `component-will-update` on the `input` component itself.  The technique described above was for a different approach:  for when you are writing a component which **contains** the `input` which is to get focus.

**Comment by marcloyal3** [comment]
Another way would be to get the current component that contains the input via reagent/dom-node and then invoke querySelector on that element, (.querySelector dom-element "input"), so you don't resort to using id's (which get defined automatically on the window object as global vars) ... Not trying to be clever, just trying to learn if that's a viable option. At any rate, I really don't like the fact that we have to target the DOM... feels so Un-Reactive to me... Does React have a way to set focus on an element in the actual DOM when the state tied to that element gets updated with say {:focus true} or something like that. In other words, can we set focus in reactive manner?

**Comment by mike-thompson-day8** [comment]
I think about it like this:  the moment you are trying to control something about the DOM and that thing can't be specified by elements and their attributes, then any React-based app will have to get the job done via a bit of imperative code in one of the the lifecycle methods.  

So, because you can't control focus via an attribute value like this mythical example:
   <input   hasfocus="true"  .... >
you have to get the job done via a bit of imperative intervention.

**Comment by marcloyal3** [comment]
@mike-thompson-day8 

How about the not-so-mythical autoFocus attribute? 

React docs says that React supports the html5 autofocus attribute but as with all attributes they are camel cased ... so setting autoFocus to true should work, tho I haven't tried it ... yet.

**Comment by marcloyal3** [comment]
autoFocus does work... Here is a demo in plain React

http://jsfiddle.net/fx6ug/2/

**Comment by mike-thompson-day8** [comment]
Good find.  That looks like it would solve @whodidthis' problem.  Just add a 
```
   [:input {:auto-focus true}  ... ]
``` 
and that `[:input ]` will have focus on initially being added to the DOM. 
  
Unfortunately, `auto-focus` only works when the control is first loaded into the DOM.  It doesn't handle the general focus problem - you can't control which input has focus and move it around. Pity.

**Comment by marcloyal3** [comment]
The user normally controls which element should have focus with mouse, touch or keyboard (tab, if enabled) I am sure there are cases where you want to set focus, just can't think of any good UX context for that right now. 

Could you reactively cause unmount to happen and then restore state from global state on mount to set focus via autoFocus,  or would that be bad?

**Comment by whodidthis** [comment]
Yeah dont actually randomly set focus in case it might be super annoying hehe.

Reason I was wondering about not depending on focus on component-did-mount is I have no idea how to do any kind of transition animation without having the element rendered but hidden away somewhere. At least with CSS. Dunno if there's some magical React.js animation thingies somewhere that enables you to do so.

Hit me up in-game if there is.

**Comment by danielytics** [comment]
@whodidthis react-with-addons has some support for CSS Transitions. It allows you to animate mount/unmount although there are a bunch of gotchas around what has to already be mounted and such - it can't animate isolated components being mounted/unmounted, but works great for lists or for transitioning pages etc.

    Too bad react doesnt have a "get element x from within this component and its children" thingie so I guess I'll agree with the document.getElementById().

Om has a concept of `refs` so you could do something like `[:input {:ref "foo"} ...]` and then `(om/get-node owner "foo")`. I wrote a simple utility version that gets the React node rather than the DOM node: `(get-ref owner "foo")`. For anyone not familiar with Om, `owner` is kinda like `reagent/current-component`.  Does reagent have something similar? Could something like it be added to re-frame if not?

I agree that, in general, one shouldn't do this and it can usually be avoided, but one place where I've used this in Om code (but haven't yet tried in reagent/re-frame, but probably will soon) is when wrapping javascript React components that provide an OO API (eg `(.toggleMenu (get-ref owner "my-menu"))`)

**Comment by whodidthis** [comment]
Om/react's ref thingie only gets element from current component but not children. Reagent doesn't have refs https://github.com/reagent-project/reagent/issues/5. You need to create components like
```clojure
(defn my-input []
  [:input...])
```
so you can access the dom element from (.getDOMNode this).

The reason refs from current component wouldn't cut it in any case is because i have a component like
```clojure
(defn login-view []
  [dialog
   [:input {:ref ???
```
where dialog is a reusable dialog component refs wouldn't be able to touch anyways. Basically I'll go with my focus on prop plan if i need to do something with dom elements hehe.

**Comment by whodidthis** [comment]
https://facebook.github.io/react/docs/animation.html CSSTransitionGroup seems to use css classes which is too much effort for me since inline styles already exist. I guess I should be looking at ReactTransitionGroup and being able to do something like
```clojure
[ReactTransitionGroup {:component "div"} ;no idea atm heh
  (case @route
    :front [front-page]
```
and mysteriously receiving more lifecycle kind of methods that im not sure how to use yet. Maybe I'll find out some interesting examples at some point

**Comment by mike-thompson-day8** [comment]
@whodidthis  Matt Greer shows how to use reagent and CSSTransitionGroup [in his game](http://www.mattgreer.org/articles/a-game-made-with-reagent/)

Would you mind closing this issue if you feel it is resolved.

**Comment by danielytics** [comment]
@mike-thompson-day8  Is there an ETA on v0.3.0? I'm very eagerly awaiting the new subscription stuff and also the change mentioned above to `after`.

**Comment by mike-thompson-day8** [comment]
@danielytics  Sorry Dan I've been completely caught up in [re-com](https://github.com/Day8/re-com) for what seems like forever.  I stalled a bit on the re-frame subscription tweaks because I could never quite get a design I was happy with.  My approach when I'm stuck is to go do something else for a while, and then to circle back later,  which I'm now doing. 

BUT I will  push the more modest 0.3 right now (its been sitting in the `develop` branch for a while).  And make the subscription tweaks the focus of 0.4.

**Comment by mike-thompson-day8** [comment]
Okay, I have pushed v0.3.0  but:
   - it is a [very modest release](https://github.com/Day8/re-frame/blob/master/CHANGES.md#v030--2015-04-15)
   - it won't be in clojars for a few hours yet

**Comment by danielytics** [comment]
Brilliant, thanks! Yeah, I figured you just got busy - happens :)

So... with that in mind, any ideas when you might have 0.4 ;-) guess I'm eager to see what you have cooking for subscriptions.

Great job on re-frame btw, fantastic piece of work.
