### ISSUE TITLE
Support Rum (and other React wrappers) for the view layer

### ISSUE THREAD

**Issue by cjhowe7** [Day8/re-frame#369]
Having the option of using Rum for the view layer would be really cool. Rum has a lot of the same primitives as Reagent - like derived atoms and cursors. What would need to go into adding this support? Is it as simple as changing the uses of Reagent to choose between React and Rum? This would make server-side rendering a lot simpler.

**Comment by mike-thompson-day8** [comment]
Rum is an excellent React wrapper but, for historical reasons, re-frame uses Reagent, and generalizing re-frame in that way is not an itch I personally or professionally need to scratch. So this work would have to be done by someone else. And I half suspect they'd be better off forking re-frame and tweaking it, rather than complicating it with generality. People tend to be all-in on Reagent or all-in on Rum.

**Comment by myguidingstar** [comment]
Fyi, I've found a fork of re-frame that targets Rum https://github.com/chpill/re-frankenstein
