### ISSUE TITLE
Dispatch handler's first argument parameter isn't a dereffed atom value

### ISSUE THREAD

**Issue by rej156** [Day8/re-frame#4]
According to the docs,
"An event handler is a pure function of two parameters:  current value in app-db. Note: that's the map in app-db, not the atom itself. 2 an event (represented as a vector)"

(defn handle-delete
  [app-state [_ cid]]          ;; notice how event vector is destructured -- 2nd parameter
  (.log js/console app-state))

app-state currently returns a reagent ratom.

This caused me major headaches understanding why 
(assoc app-state :first "hello)
wouldn't work.

Also, any idea when re-frame will be up on clojars?

**Comment by mike-thompson-day8** [comment]
Ahh, sorry.  The implementation does not currently match the words.  There is a note to that effect in the "Status" section at the top, although it is probably slightly cryptic. .

I'm actually sitting here working on that bit right now.  Once I have it sorted (a day or two?), it will be "Beta" and I'll push to Clojars.  

So just to be clear:   at the moment, the first parameter to handlers is "the app-db atom itself"  and not the value inside of the atom  (which is what I'm working on right now).

**Comment by rej156** [comment]
Hey Mike,

Thanks for the reply!
OW. My head hurt working out how to use the lein git-deps with clojurescript.
Giving the heads up for you to make it clear in the README that:
"re-frame.subs/register
re-frame.handlers/register"
don't coincide with each other etc!

Sorry was just hyped up learning about Elm + FRP with statecharts today!
Ended up reading and revamping my whole dissertation project because I discovered your README!

**Comment by mike-thompson-day8** [comment]
Instead of using git-deps,  try this:

1.  `git clone https://github.com/Day8/re-frame`
2.  `cd re-frame`
3.  `lein install`     ;; will put it in your local maven repo
4.   then, in your project.clj, put it in dependencies as if it was in clojars  ["re-frame"  "0.04"] 

Then, every now and again when re-frame advances, 
1. Pull the latest from github
2.  lein install
3.  bump the version in your project.clj

**Comment by mike-thompson-day8** [comment]
There's one other trap:  if you are baffled as to why your event handlers are not getting registered it might be this ... 

If you have out your event handlers  in their own `handlers.cljs` then you MUST put a seemingly unnecessary `require` in say your `core.cljs` to make sure that cljs file is pulled in.  

Otherwise, it can appear to Google Closure that nothing is use that file and it doesn't get put in the dependency graph and get pulled in.  (This only happens with optimisations :none).

**Comment by rej156** [comment]
Thanks for the local maven installation guideline, I was adding the git cloned repo to my cljsbuild src paths instead.
I can confirm re-frame as it is now does work with Figwheel quite nicely, the handlers overwriting warnings being logged etc.

**Comment by mike-thompson-day8** [comment]
I'll be (git) pushing version 0.1.7. within the hour  (not yet to clojars, still in repo only). 

This version introduces "handler Middleware", which is how  "pure" handlers are implemented. 

See [the Wiki](https://github.com/Day8/re-frame/wiki/Handler-Middleware).

**Comment by mike-thompson-day8** [comment]
v0.1.7 also solves your other issue.  It provides an API via `re-frame.core` which disambiguates the `register` functions.  Readme updated to match.

Usage:
```
(ns my.namespace.core
  (:require 
    [re-frame.core  :refer  [dispatch subscribe register-handler register-subs]])  ;; etc
```

**Comment by mike-thompson-day8** [comment]
Subject to getting re-frame into clojars (tomorrow), I think this issue is closable. 

@rej156  As you experiment with statecharts, please keep this repo in mind.  We're about to add a couple of sample projects.  I'd be interested in including a statechart-using example, once you have made some progress.

**Comment by rej156** [comment]
I think it's best to state that with the introduction of middleware, the default dispatch handlers are not pure?
As in to put in the README in due time!
