### ISSUE TITLE
feature suggestion: In Layer-3 subscription, the signal function allows nested maps of (sequence of) subscriptions

### ISSUE THREAD

**Issue by davidpham87** [day8/re-frame#524]
Hello, 

`signal-fn`of Layer 3 subscriptions should returns a subscription, a sequence of subscriptions or a maps of the previous ones. I think it would interesting to also allow nested maps of subscription. I guess you can avoid it query-v, but I thought it would be a nice feature.

**Comment by danielcompton** [comment]
@davidpham87 can you explain more about the motivations for this, and some example code of how you imagine it looking? I don't fully understand why you'd want to return nested maps of subscriptions?

**Comment by mike-thompson-day8** [comment]
@davidpham87  
Thank you for the idea, I understand where you are coming from. 

However, if anything, I'd like to go in the opposite direction and remove maps completely, because I now regard their inclusion as a small design mistake.  

To achieve simplicity, there should only be one way to do things (not many) and vectors alone would have been good enough.  

So, doubling down on maps is not a path I want to pursue.  Closing.

**Comment by davidpham87** [comment]
On the other hand, order induce complexity (according to the simple made easy talk), so hope you keep the one level map! But I understand your point of not supporting nested subscription. Thanks a lot four library! I really love it.
