### ISSUE TITLE
Possibility to use without Reagent?

### ISSUE THREAD

**Issue by orestis** [day8/re-frame#590]
Hey there -- re-frame is awesome, but there's a snag: It depends on Reagent.

I've found (and some others) that Reagent's async rendering breaks many packages in the React ecosystem that expect React's way of scheduling (mostly about reading the DOM for highly visual components): https://clojureverse.org/t/papercuts-with-reagent-react-integration/3882

Also with the upcoming Suspense and Concurrent Mode release, staying close to React makes some sense.

OTOH, re-frame provides a very well known and established way of doing state management the Clojure way, it would be a shame to throw all that out, and the related tooling too.

I was wondering if there's a possibility to use re-frame but implementing the rendering aspects based on pure React. I'm happy to do this work if you think the re-frame codebase is amenable to such a change. Or, if I could use re-frame as-is, and write my own adapter layer as a library?

**Comment by mike-thompson-day8** [comment]
This is a tricky topic, and I suspect I'm going to disappoint you. 

**_Situation_**: React's `class-based components` work pretty well with re-frame but `function components` with Hooks do not.   Reagent is irrelevant to this incompatibility (although historically it hasn't worked with hooks).  The problems is that Hooks provide a statefulness to components which appears, to me, to be incompatible with re-frame's state management. Maybe someone with more knowledge of Hooks will jump in a disagree with this assessment. 

For the record, I'm not currently a fan of React Hooks (but I've never used them, only read about them, so I absolutely reserve the right to change my mind). Mind you I wasn't a fan of the React world's class-based "load on mount" approach either. I just don't want my views "driving" things. Idon't want them being imperative in any way. 

Instead, I want my views providing a materialised view of the current application state. That's all. The logic in my event handlers should "drive things".  I want my components to be the V in MVC and nothing more.  And unfortunately, Facebook seems pretty committed to making them run the show (initiate HTTP GETs etc). 

Hooks might be defensible, somehow, but the Suspence stuff seems utterly crazy to me: throwing promises, right?  That just can't turn out well. And, from a re-frame point of view, completely unnecessary. 

Anyway, the problem here is that while re-frame tends to be perfectly happy working with class-based components, I currently see Hooks-based ones being more of a problem in the future because they offer an alternative state management approach,  so I can't see re-frame tracking React along these paths.

**Comment by AndrewMorsillo** [comment]
I'm a full time react-native typescript dev checking out cljs and the tooling available. I'm interested in building a side project react-native app to learn clojure. So while I know very little about the state of cljs/react interop I do have a lot of experience using hooks in react and transitioning from class based components to hooks. 

I think it boils down to this: Anything you could do with class based components you can also do with hooks. 

Most of the time it results in cleaner, easier to understand, more concise code as well. You can encapsulate and reuse logic with hooks in a way that was pretty much impossible with classes. Once you get the hang of them IMO they represent a vastly nicer, more consistent, and elegant API.

@mike-thompson-day8 I think you may have a few misunderstandings about the hooks pattern I can help with. 

* React and the hooks pattern does not force your views to be anything beyond a materialized view of the app state. Components are pure functions of their props unless you decide to build them otherwise. Hooks encourages this even more than class components did.
* It is never necessary to tie component lifecycle or rendering to mutation of app state. While you *can* do that it's usually only useful for managing effects (calling native methods, mutating dom directly, handling imperative animations, etc). Most react apps behave exactly as you're saying they should -- event handlers drive changes to the app state which is then reflected in the dom via your component functions.
* Initiating data fetching from components isn't a pattern encouraged by or core to react in my experience. Sometimes you will see components begin fetching data on load because the developer is choosing to treat "component X loaded" as an event on which to mutate app state. That really has little to do with react, you could always trigger that data load based on whatever event caused the component to be rendered in the first place. 
* In my experience any serious react app will do state management and mutation outside of the react component tree. Most use redux (IMO clunky), or my favorite mobx-state-tree (which is an awesome reactive state management library which seems quite conceptually similar to re-frame).

Since I don't understand how re-frame interacts with react (yet) can you describe how you see hooks being incompatible? I might be able to help illustrate that there's likely no compatibility issue.

**Comment by mike-thompson-day8** [comment]
I'm going to close this issue.  

I have no need to replace Reagent, which I regard as superior to the alternatives. I want to keep `re-frame` as simple as possible and not try to make it do too much. I would encourage you to fork re-frame and bend it to your preferred purposes, much as has already been done with Citrus/Rum.  re-frame is a pattern, and a set of choices, more than a codebase.

Also, I really do understand Hooks.  I just view them as a relatively mediocre solution.  Not terrible, just mediocre and uninteresting. And most likely a largely failed dead-end within two years. To me, they are just another chapter in the endless javascript churn story, which involves lots, and lots of breathlessly running around after new shiny things, which turn out to be not that great.  We're now also seeing a frantic rush towards recoiljs too.  re-frame has had better solutions for 6 years. 

In summary, it has been a competitive advantage to actively ignore this javascript churn. React v1 was a wonderful game changer. We all saw that very quickly and jumped on board. But what has happened since then is distinctly meh. 

It seems to me that the React team has fallen for a Cognitive bias which can be stated as ["What is focal is presumed focal"](http://day8.github.io/re-frame/FAQs/LoadOnMount/#for-javascript-the-developer). 

Having said that, I'm interested in Hooks to the extent that I'd like access to React components libraries to the greatest extent possible (but no more).

And as for React Suspense ... double meh. Just not that important for my kinds of applications. And, if it were, I would do it another, more straightforward way. I'd be MUCH more excited if they chose to solve these kinds of problems using a data-oriented architecture allowing simple communication between SharedWorkers (which appear to be slowly happening, after a rocky start).  The React teams have just tied themselves in knots (very delayed releases, complicated codebase, etc) and limited their future options. Which is a pity. 

But that's just me.  If you enjoy surfing the churn ... fork with my blessing and I look forward to being wrong and using your better solution in the future :-)

**Comment by orestis** [comment]
Thanks for a detailed response, I really appreciate it. And thanks for blessing the world with re-frame :)
