### ISSUE TITLE
Consider multimethods over register function

### ISSUE THREAD

**Issue by tomconnors** [Day8/re-frame#6]
You could define `handle-subscribe` and a `handle-dispatch` multimethods and have no need to manually register handlers. Does this sound like a good idea to you?

**Comment by mike-thompson-day8** [comment]
My initial implementation used multimethods.  I'm trying to remember why I moved away from that.  Was there a problem with the way figwheel can reload multimethods?  Or maybe because I thought (mistakenly) that we'd need to register and deregister handlers?  Or was it because I heard that multimethods are slow, or something.  Or did I plan to achieve the equivalent of multimethods via use of a macro (best of both worlds?).  I can't quite remember. 

Irrespective, at this point, I'd like to stick with the long term flexibility of registration over the slight convenience of multi-methods.

**Comment by mike-thompson-day8** [comment]
Also, at one point, when investigating some Flux implementations,  I wondered if we'd need to support having more than one handler registered for an event.  Flux allows for all sorts of things;  one handler "waiting" for another etc.  Didn't ever happen in re-frame (yet), but it left me a feeling the need to default to the most flexible arrangement.

**Comment by mike-thompson-day8** [comment]
Closing this. See the latest steps in [the Wiki](https://github.com/Day8/re-frame/wiki/Handler-Middleware)

**Comment by tomconnors** [comment]
Thanks for explaining your reasoning on this.
