### ISSUE TITLE
Use pre and post conditions instead of manual validations

### ISSUE THREAD

**Issue by danielcompton** [Day8/re-frame#63]
I'm not sure if this is a good idea or not, but I'm opening it up for discussion. Through the re-frame codebase there are validations done like https://github.com/Day8/re-frame/blob/master/src/re_frame/utils.cljs#L41-L45 which are really validating pre-conditions on the arguments. The intent of the code would be clearer if preconditions were used, although that brings up the question of how you want to handle errors when preconditions fail.

Thoughts?

**Comment by danielcompton** [comment]
Some reading material on the subject
http://swannodette.github.io/2015/01/09/life-with-dynamic-typing/
http://swannodette.github.io/2015/01/10/faster-validation-through-immutability/
http://swannodette.github.io/2015/01/12/lazy-contracts/

**Comment by mike-thompson-day8** [comment]
Once, a long time ago, I read Bertrand Meyer's books and wrote a few Eiffel programs, so I'm a big fan of pre and post conditions in general  (he is the source of the movement). 

Except I'm also a fan of being as kind as possible to the the programmer, and giving the best possible error messages.  The case you highlight is meant to catch this oft-made, easy mistake: 

  - writing `(dispatch   :blah)`   
  - instead of   `(dispatch [:blah])`     

Ie. `dispatch` should be given a vector, but at some point or other we all forget that.  So I wanted to produce the kindest possible message for this common mistake. 

So  the considerations are: 
  -  maximising the quality of error message.  I seem to remember getting ugly messages out of `pre` by default - perhaps I didn't try hard enough?
  - At one time, I was also a bit leary of throwing exceptions (via pre) because the figwheel/reagent combination seemed to not recover well from certain kinds of exceptions.  So I opted for not throwing, just writing to console. 
  - `error` is plugable. Works in with whatever logging system someone wants to use.

**Comment by mike-thompson-day8** [comment]
I'm going to close this.  But happy to reopen is more discussion required.
